const allproducts = [
  {
    product_id: 1,
    name: "Dark Roast Coffee",
    price: 10.99,
    description: "Rich, dark and full-bodied coffee with a robust flavor.",
    product_image_path: "/assets/img/products/coffee/dark-roast.png",
    quantity_in_stock: 50,
    category_name: "Coffee",
  },
  {
    product_id: 2,
    name: "Medium Roast Coffee",
    price: 9.99,
    description: "Balanced, smooth, and rich coffee with mild acidity.",
    product_image_path: "/assets/img/products/coffee/medium-roast.png",
    quantity_in_stock: 45,
    category_name: "Coffee",
  },
  {
    product_id: 3,
    name: "Light Roast Coffee",
    price: 8.99,
    description: "Bright, fruity, and mild coffee with a light body.",
    product_image_path: "/assets/img/products/coffee/light-roast.png",
    quantity_in_stock: 55,
    category_name: "Coffee",
  },
  {
    product_id: 4,
    name: "Green Tea",
    price: 5.99,
    description: "Refreshing and healthy green tea with a delicate flavor.",
    product_image_path: "/assets/img/products/tea/green-tea.png",
    quantity_in_stock: 65,
    category_name: "Coffee",
  },
  {
    product_id: 5,
    name: "Black Tea",
    price: 6.99,
    description: "Bold and full-bodied black tea with a rich aroma.",
    product_image_path: "/assets/img/products/tea/black-tea.png",
    quantity_in_stock: 60,
    category_name: "Tea",
  },
  {
    product_id: 6,
    name: "Herbal Tea",
    price: 7.99,
    description: "Soothing and caffeine-free herbal tea with a blend of herbs.",
    product_image_path: "/assets/img/products/tea/herbal-tea.png",
    quantity_in_stock: 40,
    category_name: "Tea",
  },
  {
    product_id: 10,
    name: "Coffee Grinder",
    price: 29.99,
    description: "Efficient and easy-to-use coffee grinder for a perfect brew.",
    product_image_path: "/assets/img/products/equipment/coffee-grinder.png",
    quantity_in_stock: 7,
    category_name: "Equipment", //
  },
];

export default allproducts;
