const allproducts = [
  {
    product_id: 1,
    name: "Dark Roast Coffee",
    price: 10.99,
    description: "Rich, dark and full-bodied coffee with a robust flavor.",
    product_image_path: "/assets/img/products/coffee/dark-roast.png",
    quantity_in_stock: 50,
    category_id: 1,
  },
  {
    product_id: 2,
    name: "Medium Roast Coffee",
    price: 9.99,
    description: "Balanced, smooth, and rich coffee with mild acidity.",
    product_image_path: "/assets/img/products/coffee/medium-roast.png",
    quantity_in_stock: 45,
    category_id: 1,
  },
  {
    product_id: 3,
    name: "Light Roast Coffee",
    price: 8.99,
    description: "Bright, fruity, and mild coffee with a light body.",
    product_image_path: "/assets/img/products/coffee/light-roast.png",
    quantity_in_stock: 55,
    category_id: 1,
  },
  {
    product_id: 4,
    name: "Green Tea",
    price: 5.99,
    description: "Refreshing and healthy green tea with a delicate flavor.",
    product_image_path: "/assets/img/products/tea/green-tea.png",
    quantity_in_stock: 65,
    category_id: 2,
  },
  {
    product_id: 5,
    name: "Black Tea",
    price: 6.99,
    description: "Bold and full-bodied black tea with a rich aroma.",
    product_image_path: "/assets/img/products/tea/black-tea.png",
    quantity_in_stock: 60,
    category_id: 2,
  },
  {
    product_id: 6,
    name: "Herbal Tea",
    price: 7.99,
    description: "Soothing and caffeine-free herbal tea with a blend of herbs.",
    product_image_path: "/assets/img/products/tea/herbal-tea.png",
    quantity_in_stock: 40,
    category_id: 2,
  },
  {
    product_id: 7,
    name: "Chocolate Chip Cookies",
    price: 4.99,
    description: "Delicious and crunchy cookies packed with chocolate chips.",
    product_image_path:
      "/assets/img/products/snacks/chocolate-chip-cookies.png",
    quantity_in_stock: 80,
    category_id: 3,
  },
  {
    product_id: 8,
    name: "Mixed Nuts",
    price: 3.99,
    description: "Healthy and tasty mix of almonds, cashews, and walnuts.",
    product_image_path: "/assets/img/products/snacks/mixed-nuts.png",
    quantity_in_stock: 75,
    category_id: 3,
  },
  {
    product_id: 9,
    name: "Granola Bars",
    price: 2.99,
    description: "Wholesome and energizing granola bars with oats and honey.",
    product_image_path: "/assets/img/products/snacks/granola-bars.png",
    quantity_in_stock: 90,
    category_id: 3,
  },
  {
    product_id: 10,
    name: "Coffee Grinder",
    price: 29.99,
    description: "Efficient and easy-to-use coffee grinder for a perfect brew.",
    product_image_path: "/assets/img/products/equipment/coffee-grinder.png",
    quantity_in_stock: 7,
    category_id: 4, // Add the category_id field here
  },
];

export default allproducts;
