// Dummy data for customers
const customers = [
  {
    user_id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    phone_number: "555-123-4567",
    postal_code: "12345",
    address: "123 Main St, Anytown",
  },
  {
    user_id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone_number: "555-234-5678",
    postal_code: "23456",
    address: "456 Elm St, Anytown",
  },
  {
    user_id: 3,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    phone_number: "555-345-6789",
    postal_code: "34567",
    address: "789 Pine St, Anytown",
  },
  {
    user_id: 4,
    name: "Emily Davis",
    email: "emily.davis@example.com",
    phone_number: "555-456-7890",
    postal_code: "45678",
    address: "101 Oak St, Anytown",
  },
  {
    user_id: 5,
    name: "William Johnson",
    email: "william.johnson@example.com",
    phone_number: "555-567-8901",
    postal_code: "56789",
    address: "202 Maple St, Anytown",
  },
  {
    user_id: 6,
    name: "Sophia Martinez",
    email: "sophia.martinez@example.com",
    phone_number: "555-678-9012",
    postal_code: "67890",
    address: "303 Walnut St, Anytown",
  },
  {
    user_id: 7,
    name: "James Wilson",
    email: "james.wilson@example.com",
    phone_number: "555-789-0123",
    postal_code: "78901",
    address: "404 Cherry St, Anytown",
  },
  {
    user_id: 8,
    name: "Olivia Garcia",
    email: "olivia.garcia@example.com",
    phone_number: "555-890-1234",
    postal_code: "89012",
    address: "505 Birch St, Anytown",
  },
  {
    user_id: 9,
    name: "Alexander Taylor",
    email: "alexander.taylor@example.com",
    phone_number: "555-901-2345",
    postal_code: "90123",
    address: "606 Cedar St, Anytown",
  },
  {
    user_id: 10,
    name: "Charlotte Anderson",
    email: "charlotte.anderson@example.com",
    phone_number: "555-012-3456",
    postal_code: "01234",
    address: "707 Spruce St, Anytown",
  },
];

export default customers;
